# -*- coding: utf-8 -*-
"""score_predictor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjOTjPm3fvLTA0OIJRf_l2Qt37DhhTaF
"""

import streamlit as st
import pandas as pd
import pickle
import numpy as np

# Load the pre-trained model
cricket_score = pickle.load(open('score_prediction.pkl', 'rb'))

# Streamlit App Title
st.title('T20 Cricket Score Predictor')


# Function to get user input
def get_user_input():
    batting_team = st.selectbox('Select Batting Team', [ 'Australia', 'India', 'Bangladesh', 'New Zealand', 'South Africa',
    'England', 'West Indies', 'Afghanistan', 'Pakistan', 'Sri Lanka'])
    bowling_team = st.selectbox('Select Bowling Team', [ 'Australia', 'India', 'Bangladesh', 'New Zealand', 'South Africa',
    'England', 'West Indies', 'Afghanistan', 'Pakistan', 'Sri Lanka'])
    city = st.selectbox('Select City', ['Colombo', 'Mirpur', 'Johannesburg', 'Dubai', 'Auckland', 'Cape Town',
    'London', 'Pallekele', 'Barbados', 'Sydney', 'Melbourne', 'Durban',
    'St Lucia', 'Wellington', 'Lauderhill', 'Hamilton', 'Centurion',
    'Manchester', 'Abu Dhabi', 'Mumbai', 'Nottingham', 'Southampton',
    'Mount Maunganui', 'Chittagong', 'Kolkata', 'Lahore', 'Delhi',
    'Nagpur', 'Chandigarh', 'Adelaide', 'Bangalore', 'St Kitts', 'Cardiff',
    'Christchurch', 'Trinidad'])  # Replace with actual city names
    current_score = st.number_input('Current Score', min_value=0, max_value=300, value=50)
    balls_left = st.number_input('Balls Left', min_value=0, max_value=120, value=60)
    wickets_left = st.number_input('Wickets Left', min_value=0, max_value=10, value=5)
    current_runrate = st.number_input('Current Run Rate', min_value=0.0, value=6.0)

    user_input_data = {
        'batting_team': batting_team,
        'bowling_team': bowling_team,
        'city': city,
        'current_score': current_score,
        'balls_left': balls_left,
        'wicket_left': wickets_left,
        'current_runrate': current_runrate
    }

    return pd.DataFrame(user_input_data, index=[0])


# Get user input
user_input = get_user_input()

# Display user input
st.write("### User Input:")
st.write(user_input)

# Prediction button
if st.button('Predict Final Score'):
    # Make predictions
    prediction = cricket_score.predict(user_input)
    st.write(f"### Predicted Final Score is : {prediction[0]:.0f}")